// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '../components/Navbar'; // Import Navbar component
import "./globals.css";

import { Suspense } from "react";



// Font setup
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the app
export const metadata = {
  title: "CHOP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <Navbar />
        <Suspense fallback={<div>Loading...</div>}>
          {children}
        </Suspense>
        <footer className="py-4 text-center text-gray-500">
          <p className="text-sm">Powered by ChopAPI</p>
        </footer>
      </body>
    </html>
  );
}

